apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pingpong
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/minScale: "0"  # Scale to zero when idle
        autoscaling.knative.dev/maxScale: "10"  # Max 10 instances
    spec:
      containers:
        - image: pingpong:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "pingpong"
            - name: DB_USER
              value: "pingpong"
            - name: DB_PASSWORD
              value: "pingpong"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

